# Generated by Django 3.0.3 on 2020-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0003_auto_20200711_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
