# Generated by Django 3.0.3 on 2020-07-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0004_auto_20200711_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('github_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('twitter_url', models.URLField()),
            ],
        ),
    ]
