# Generated by Django 3.0.3 on 2020-07-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
